title: Ceramic
description: >
  Common Lisp web applications on the desktop.
url: "http://ceramic.github.io"
baseurl: ""

links:
  chat: todo
  docs: /docs/introduction.html
  tutorial: /docs/tutorial.html
  api: /docs/api-reference.html
  markedit: https://github.com/ceramic/markedit/
  repo: https://github.com/ceramic/ceramic
  org: https://github.com/ceramic
  issues: https://github.com/ceramic/ceramic/issues
  electron: http://electron.atom.io
  atom: https://atom.io
  
