title: Ceramic
description: >
  Common Lisp web applications on the desktop.
url: "http://ceramic.github.io"
baseurl: ""

links:
  docs: /docs/introduction.html
  github: https://github.com/ceramic
  repo: https://github.com/ceramic/ceramic
